import { GeneratedFile } from "@/context/AppContext";

// Simulated AI generation - produces a React project structure
export async function generateProject(
  prompt: string,
  existingFiles: GeneratedFile[],
  onLoadingMessage: (msg: string) => void
): Promise<GeneratedFile[]> {
  const { funnyLoadingMessages } = await import("@/context/AppContext");

  // Cycle through funny loading messages
  let msgIndex = 0;
  const interval = setInterval(() => {
    onLoadingMessage(funnyLoadingMessages[msgIndex % funnyLoadingMessages.length]);
    msgIndex++;
  }, 1800);

  // Simulate generation delay
  await new Promise(r => setTimeout(r, 3000 + Math.random() * 2000));
  clearInterval(interval);

  const lowerPrompt = prompt.toLowerCase();

  // Generate different templates based on prompt keywords
  if (lowerPrompt.includes("login") || lowerPrompt.includes("auth")) {
    return generateAuthTemplate(prompt);
  }
  if (lowerPrompt.includes("dashboard") || lowerPrompt.includes("admin")) {
    return generateDashboardTemplate(prompt);
  }
  if (lowerPrompt.includes("todo") || lowerPrompt.includes("task")) {
    return generateTodoTemplate(prompt);
  }
  if (lowerPrompt.includes("landing") || lowerPrompt.includes("portfolio")) {
    return generateLandingTemplate(prompt);
  }
  if (lowerPrompt.includes("e-commerce") || lowerPrompt.includes("shop") || lowerPrompt.includes("store")) {
    return generateEcommerceTemplate(prompt);
  }

  // Default: generate based on existing files or create new
  if (existingFiles.length > 0) {
    return generateIterativeUpdate(prompt, existingFiles);
  }

  return generateDefaultTemplate(prompt);
}

function generateDefaultTemplate(prompt: string): GeneratedFile[] {
  return [
    {
      name: "index.html",
      path: "/index.html",
      language: "html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Generated App</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div id="app">
    <header class="header">
      <h1>✨ ${prompt.slice(0, 40)}</h1>
      <nav>
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="#contact">Contact</a>
      </nav>
    </header>
    <main class="main">
      <section class="hero">
        <h2>Welcome to Your App</h2>
        <p>Built with AI magic from your prompt: "${prompt.slice(0, 80)}"</p>
        <button class="btn-primary" onclick="alert('🎉 It works!')">Get Started</button>
      </section>
    </main>
    <footer class="footer">
      <p>Built with Laughable AI 🤖</p>
    </footer>
  </div>
  <script src="app.js"></script>
</body>
</html>`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      language: "css",
      content: `* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: 'Segoe UI', system-ui, sans-serif;
  background: #0a0a0a;
  color: #e0e0e0;
  min-height: 100vh;
}
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
  background: #111;
  border-bottom: 1px solid #222;
}
.header h1 { font-size: 1.25rem; color: #00ff88; }
.header nav a {
  color: #888;
  text-decoration: none;
  margin-left: 1.5rem;
  transition: color 0.2s;
}
.header nav a:hover { color: #00ff88; }
.hero {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 70vh;
  text-align: center;
  padding: 2rem;
}
.hero h2 {
  font-size: 3rem;
  margin-bottom: 1rem;
  background: linear-gradient(135deg, #00ff88, #00bcd4);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
.hero p { color: #888; margin-bottom: 2rem; max-width: 500px; }
.btn-primary {
  padding: 0.75rem 2rem;
  background: #00ff88;
  color: #000;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  font-size: 1rem;
  transition: transform 0.2s, box-shadow 0.2s;
}
.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 0 20px rgba(0, 255, 136, 0.3);
}
.footer {
  text-align: center;
  padding: 2rem;
  color: #555;
  border-top: 1px solid #222;
}`,
    },
    {
      name: "app.js",
      path: "/app.js",
      language: "javascript",
      content: `// App logic
console.log('🚀 App generated by Laughable AI');

document.addEventListener('DOMContentLoaded', () => {
  console.log('App is ready!');
  
  // Add smooth scroll
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });
});`,
    },
    {
      name: "README.md",
      path: "/README.md",
      language: "markdown",
      content: `# Generated App

> Built with Laughable AI 🤖

## Prompt
${prompt}

## Getting Started
Open \`index.html\` in your browser. That's it. We're not rocket scientists.
`,
    },
  ];
}

function generateAuthTemplate(_prompt: string): GeneratedFile[] {
  return [
    {
      name: "index.html",
      path: "/index.html",
      language: "html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login - Generated App</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h1>🔐 Welcome Back</h1>
        <p>Sign in to your account</p>
      </div>
      <form id="loginForm" class="auth-form">
        <div class="form-group">
          <label>Email</label>
          <input type="email" id="email" placeholder="you@example.com" required />
        </div>
        <div class="form-group">
          <label>Password</label>
          <input type="password" id="password" placeholder="••••••••" required />
        </div>
        <button type="submit" class="btn-primary">Sign In</button>
        <p class="auth-switch">Don't have an account? <a href="#" id="switchToRegister">Sign Up</a></p>
      </form>
    </div>
  </div>
  <script src="auth.js"></script>
</body>
</html>`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      language: "css",
      content: `* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: 'Segoe UI', system-ui, sans-serif;
  background: #0a0a0a;
  color: #e0e0e0;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
}
.auth-container { width: 100%; max-width: 420px; padding: 1rem; }
.auth-card {
  background: #111;
  border: 1px solid #222;
  border-radius: 16px;
  padding: 2.5rem;
}
.auth-header { text-align: center; margin-bottom: 2rem; }
.auth-header h1 { font-size: 1.75rem; color: #00ff88; }
.auth-header p { color: #666; margin-top: 0.5rem; }
.form-group { margin-bottom: 1.25rem; }
.form-group label { display: block; margin-bottom: 0.5rem; color: #888; font-size: 0.875rem; }
.form-group input {
  width: 100%;
  padding: 0.75rem 1rem;
  background: #0a0a0a;
  border: 1px solid #333;
  border-radius: 8px;
  color: #e0e0e0;
  font-size: 1rem;
  outline: none;
  transition: border-color 0.2s;
}
.form-group input:focus { border-color: #00ff88; }
.btn-primary {
  width: 100%;
  padding: 0.75rem;
  background: #00ff88;
  color: #000;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  font-size: 1rem;
  margin-top: 0.5rem;
  transition: opacity 0.2s;
}
.btn-primary:hover { opacity: 0.9; }
.auth-switch { text-align: center; margin-top: 1.5rem; color: #666; font-size: 0.875rem; }
.auth-switch a { color: #00ff88; text-decoration: none; }`,
    },
    {
      name: "auth.js",
      path: "/auth.js",
      language: "javascript",
      content: `// Demo authentication logic
const users = JSON.parse(localStorage.getItem('laughable_users') || '[]');

document.getElementById('loginForm').addEventListener('submit', (e) => {
  e.preventDefault();
  const email = document.getElementById('email').value;
  const password = document.getElementById('password').value;
  
  const user = users.find(u => u.email === email && u.password === password);
  if (user) {
    alert('🎉 Login successful! Welcome back, ' + email);
    localStorage.setItem('laughable_session', JSON.stringify({ email }));
  } else {
    alert('❌ Invalid credentials. Try registering first!');
  }
});

console.log('🔐 Auth system loaded (demo mode - DO NOT use in production!)');`,
    },
    {
      name: "db.json",
      path: "/api/db.json",
      language: "json",
      content: `{
  "users": [],
  "sessions": [],
  "_note": "This is a demo JSON database. In production, use a real database!"
}`,
    },
  ];
}

function generateDashboardTemplate(_prompt: string): GeneratedFile[] {
  return [
    {
      name: "index.html",
      path: "/index.html",
      language: "html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Dashboard</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div class="dashboard">
    <aside class="sidebar">
      <div class="sidebar-logo">📊 Dashboard</div>
      <nav>
        <a href="#" class="nav-item active">🏠 Overview</a>
        <a href="#" class="nav-item">📈 Analytics</a>
        <a href="#" class="nav-item">👥 Users</a>
        <a href="#" class="nav-item">⚙️ Settings</a>
      </nav>
    </aside>
    <main class="content">
      <header class="topbar">
        <h2>Overview</h2>
        <div class="user-badge">👤 Admin</div>
      </header>
      <div class="stats-grid">
        <div class="stat-card"><h3>1,234</h3><p>Total Users</p></div>
        <div class="stat-card"><h3>$12.4k</h3><p>Revenue</p></div>
        <div class="stat-card"><h3>89%</h3><p>Uptime</p></div>
        <div class="stat-card"><h3>42</h3><p>Active Now</p></div>
      </div>
      <div class="chart-placeholder">
        <p>📊 Chart goes here (imagine beautiful graphs)</p>
      </div>
    </main>
  </div>
</body>
</html>`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      language: "css",
      content: `* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Segoe UI', sans-serif; background: #0a0a0a; color: #e0e0e0; }
.dashboard { display: flex; min-height: 100vh; }
.sidebar {
  width: 240px; background: #111; border-right: 1px solid #222;
  padding: 1.5rem 1rem; display: flex; flex-direction: column; gap: 0.5rem;
}
.sidebar-logo { font-size: 1.25rem; font-weight: 700; color: #00ff88; padding: 0 0.5rem; margin-bottom: 1.5rem; }
.nav-item {
  display: block; padding: 0.75rem 1rem; color: #888; text-decoration: none;
  border-radius: 8px; transition: all 0.2s;
}
.nav-item:hover, .nav-item.active { background: #1a1a1a; color: #00ff88; }
.content { flex: 1; padding: 1.5rem 2rem; }
.topbar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; }
.user-badge { background: #1a1a1a; padding: 0.5rem 1rem; border-radius: 8px; font-size: 0.875rem; }
.stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }
.stat-card {
  background: #111; border: 1px solid #222; border-radius: 12px; padding: 1.5rem;
}
.stat-card h3 { font-size: 1.75rem; color: #00ff88; margin-bottom: 0.25rem; }
.stat-card p { color: #666; font-size: 0.875rem; }
.chart-placeholder {
  background: #111; border: 1px solid #222; border-radius: 12px; padding: 4rem;
  text-align: center; color: #555;
}`,
    },
  ];
}

function generateTodoTemplate(_prompt: string): GeneratedFile[] {
  return [
    {
      name: "index.html",
      path: "/index.html",
      language: "html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo App</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div class="app">
    <h1>✅ Todo App</h1>
    <div class="add-todo">
      <input type="text" id="todoInput" placeholder="What needs to be done?" />
      <button onclick="addTodo()">Add</button>
    </div>
    <ul id="todoList" class="todo-list"></ul>
    <div class="stats" id="stats"></div>
  </div>
  <script src="app.js"></script>
</body>
</html>`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      language: "css",
      content: `* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Segoe UI', sans-serif; background: #0a0a0a; color: #e0e0e0; min-height: 100vh; display: flex; justify-content: center; padding-top: 4rem; }
.app { width: 100%; max-width: 500px; padding: 1rem; }
h1 { text-align: center; margin-bottom: 2rem; color: #00ff88; }
.add-todo { display: flex; gap: 0.5rem; margin-bottom: 1.5rem; }
.add-todo input { flex: 1; padding: 0.75rem 1rem; background: #111; border: 1px solid #333; border-radius: 8px; color: #e0e0e0; font-size: 1rem; outline: none; }
.add-todo input:focus { border-color: #00ff88; }
.add-todo button { padding: 0.75rem 1.5rem; background: #00ff88; color: #000; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; }
.todo-list { list-style: none; }
.todo-item { display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem; background: #111; border: 1px solid #222; border-radius: 8px; margin-bottom: 0.5rem; }
.todo-item.done { opacity: 0.5; text-decoration: line-through; }
.todo-item input[type="checkbox"] { accent-color: #00ff88; }
.todo-item .delete { margin-left: auto; color: #ff4444; cursor: pointer; background: none; border: none; font-size: 1.25rem; }
.stats { text-align: center; color: #555; margin-top: 1.5rem; font-size: 0.875rem; }`,
    },
    {
      name: "app.js",
      path: "/app.js",
      language: "javascript",
      content: `let todos = JSON.parse(localStorage.getItem('laughable_todos') || '[]');
renderTodos();

function addTodo() {
  const input = document.getElementById('todoInput');
  if (!input.value.trim()) return;
  todos.push({ id: Date.now(), text: input.value.trim(), done: false });
  input.value = '';
  save();
  renderTodos();
}

document.getElementById('todoInput').addEventListener('keypress', (e) => {
  if (e.key === 'Enter') addTodo();
});

function toggleTodo(id) {
  todos = todos.map(t => t.id === id ? { ...t, done: !t.done } : t);
  save();
  renderTodos();
}

function deleteTodo(id) {
  todos = todos.filter(t => t.id !== id);
  save();
  renderTodos();
}

function save() {
  localStorage.setItem('laughable_todos', JSON.stringify(todos));
}

function renderTodos() {
  const list = document.getElementById('todoList');
  list.innerHTML = todos.map(t => \`
    <li class="todo-item \${t.done ? 'done' : ''}">
      <input type="checkbox" \${t.done ? 'checked' : ''} onchange="toggleTodo(\${t.id})" />
      <span>\${t.text}</span>
      <button class="delete" onclick="deleteTodo(\${t.id})">×</button>
    </li>
  \`).join('');
  const done = todos.filter(t => t.done).length;
  document.getElementById('stats').textContent = \`\${done}/\${todos.length} completed\`;
}`,
    },
  ];
}

function generateLandingTemplate(prompt: string): GeneratedFile[] {
  return generateDefaultTemplate(prompt);
}

function generateEcommerceTemplate(_prompt: string): GeneratedFile[] {
  return [
    {
      name: "index.html",
      path: "/index.html",
      language: "html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Shop</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="header">
    <h1>🛍️ AI Shop</h1>
    <div class="cart-badge" id="cartBadge">🛒 0</div>
  </header>
  <main class="products" id="products"></main>
  <script src="app.js"></script>
</body>
</html>`,
    },
    {
      name: "styles.css",
      path: "/styles.css",
      language: "css",
      content: `* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Segoe UI', sans-serif; background: #0a0a0a; color: #e0e0e0; }
.header { display: flex; justify-content: space-between; align-items: center; padding: 1rem 2rem; background: #111; border-bottom: 1px solid #222; }
.header h1 { color: #00ff88; font-size: 1.25rem; }
.cart-badge { background: #1a1a1a; padding: 0.5rem 1rem; border-radius: 8px; cursor: pointer; }
.products { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1.5rem; padding: 2rem; }
.product-card { background: #111; border: 1px solid #222; border-radius: 12px; padding: 1.5rem; transition: transform 0.2s; }
.product-card:hover { transform: translateY(-4px); }
.product-card .emoji { font-size: 3rem; text-align: center; margin-bottom: 1rem; }
.product-card h3 { margin-bottom: 0.5rem; }
.product-card .price { color: #00ff88; font-size: 1.25rem; font-weight: 700; margin-bottom: 1rem; }
.product-card button { width: 100%; padding: 0.5rem; background: #00ff88; color: #000; border: none; border-radius: 6px; font-weight: 600; cursor: pointer; }`,
    },
    {
      name: "app.js",
      path: "/app.js",
      language: "javascript",
      content: `const products = [
  { id: 1, name: 'AI Widget', price: 29.99, emoji: '🤖' },
  { id: 2, name: 'Cloud Storage', price: 9.99, emoji: '☁️' },
  { id: 3, name: 'Pixel Pack', price: 14.99, emoji: '🎨' },
  { id: 4, name: 'Code Snippets', price: 4.99, emoji: '💻' },
  { id: 5, name: 'Debug Tool', price: 19.99, emoji: '🐛' },
  { id: 6, name: 'API Credits', price: 49.99, emoji: '⚡' },
];
let cart = [];

function renderProducts() {
  document.getElementById('products').innerHTML = products.map(p => \`
    <div class="product-card">
      <div class="emoji">\${p.emoji}</div>
      <h3>\${p.name}</h3>
      <div class="price">$\${p.price}</div>
      <button onclick="addToCart(\${p.id})">Add to Cart</button>
    </div>
  \`).join('');
}

function addToCart(id) {
  cart.push(id);
  document.getElementById('cartBadge').textContent = '🛒 ' + cart.length;
}

renderProducts();`,
    },
  ];
}

function generateIterativeUpdate(prompt: string, existingFiles: GeneratedFile[]): GeneratedFile[] {
  // For iterative updates, modify existing files with a comment
  return existingFiles.map(file => {
    if (file.language === "html") {
      return {
        ...file,
        content: file.content.replace(
          "</body>",
          `  <!-- Updated based on: "${prompt.slice(0, 60)}" -->\n</body>`
        ),
      };
    }
    if (file.language === "css") {
      return {
        ...file,
        content: file.content + `\n\n/* Update: ${prompt.slice(0, 60)} */\n.updated { color: #00ff88; }\n`,
      };
    }
    return file;
  });
}
